# -*- coding: utf-8 -*-
"""Soma em python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VXBOjL5oSpUN5LG8bStvGuOdYTDNVE14
"""

numéro1 = input("Digite um número aqui")
numéro2 = input("Digite outro número aqui")

resultado = int(numéro1) + int(numéro2)
print("O resultado da operação é: " + str(resultado))